on:
  push:
    branches:
      - main
  workflow_dispatch:

name: deploy_main
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.22.1]

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: set branch
        id: branch
        run: echo "::set-output name=branch::oper"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=Asia/Seoul date +'%Y%m%d_%H%M')"

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: giftistar/pm2-nest-server-env
          tags: |
            type=raw,value=12.22.1
            type=raw,value=date_${{ steps.date.outputs.date }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
